"""Narrow, deterministic TI PSpice-to-ngspice compatibility translation."""

from __future__ import annotations

import re


TRANSLATOR_REVISION = "headgames-ti-lmx58-ngspice-v7"


def _spice_number(token: str) -> float:
    match = re.fullmatch(r"([+-]?\d+(?:\.\d+)?(?:e[+-]?\d+)?)(meg|[tgkmunpf]?)", token, re.I)
    if not match:
        raise ValueError(f"unsupported SPICE number {token!r}")
    scales = {"": 1.0, "t": 1e12, "g": 1e9, "meg": 1e6, "k": 1e3,
              "m": 1e-3, "u": 1e-6, "n": 1e-9, "p": 1e-12, "f": 1e-15}
    return float(match.group(1)) * scales[match.group(2).lower()]


def _switch(match: re.Match[str]) -> str:
    prefix, body = match.groups()
    von = re.search(r"(?i)\bVon\s*=\s*([^\s)]+)", body)
    voff = re.search(r"(?i)\bVoff\s*=\s*([^\s)]+)", body)
    if von is None or voff is None:
        raise ValueError("VSWITCH lacks Von/Voff")
    on, off = _spice_number(von.group(1)), _spice_number(voff.group(1))
    body = re.sub(r"(?i)\bVon\s*=\s*[^\s)]+", f"VT={(on+off)/2:.12g}", body)
    body = re.sub(r"(?i)\bVoff\s*=\s*[^\s)]+", f"VH={abs(on-off)/2:.12g}", body)
    return prefix + "SW(" + body.strip() + ")"


def _table(match: re.Match[str]) -> str:
    prefix, expression, rows = match.groups()
    points = []
    for left, right in re.findall(r"\(\s*([^,]+),\s*([^\)]+)\)", rows):
        points.extend((left.strip(), right.strip()))
    if not points:
        raise ValueError("controlled-source TABLE has no points")
    return f"{prefix}VALUE={{pwl({expression.strip()}, {', '.join(points)})}}\n"


def translate_ti_lmx58(source: str) -> str:
    """Translate only constructs observed in TI's hash-locked Rev. B model."""
    translated = re.sub(
        r"(?im)^(\.model\s+\S+\s+)VSWITCH\s*\(([^\n)]*)\)", _switch, source
    )
    translated = re.sub(
        r"(?im)^(G\S+\s+\S+\s+\S+\s+)TABLE\s*\{([^}]*)\}\s*=\s*\n((?:\+\s*\([^\n]+\)\s*\n)+)",
        _table, translated,
    )
    translated = re.sub(r"(?i)\bIF\s*\(", "ternary_fcn(", translated)
    translated = translated.replace(" | ", " || ")
    banner = (
        f"* GENERATED BY {TRANSLATOR_REVISION}; DO NOT EDIT\n"
        "* Source remains models/ti/lmx58_lm2904.lib\n"
    )
    normalized = "\n".join(line.rstrip() for line in translated.splitlines()).rstrip() + "\n"
    return banner + normalized
